matrix:
  include:
    - language: node_js
      node_js:
        - "9"
      before_install:
        - cd node/push/
      install: 
        - npm install
      script:
        - npm test

    - language: node_js
      node_js:
        - "9"
      before_install:
        - cd node/fetch-galo/
      install:
        - npm install
      script:
        - npm test


notifications:
  email:
    on_success: never
    on_failure: always
