service: goals-tracker-project

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: eu-north-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
      Resource:
        - { "Fn::GetAtt": ["SubscriptionsTable", "Arn" ] }
        - { "Fn::GetAtt": ["EventsTable", "Arn" ] }

functions:
  subscriber:
    handler: subscriber/index.handler
    events:
      - http:
          path: subscription
          method: post
          cors: true

  fetch:
    handler: fetch/index.handler
    events:
      - schedule: rate(1 minute)

package:
  exclude:
    - "node_modules/aws-sdk/**"

resources:
  Resources:
    SubscriptionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: SubscriptionsTable
        AttributeDefinitions:
          - AttributeName: endpoint
            AttributeType: S
        KeySchema:
          - AttributeName: endpoint
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    EventsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventsTable
        AttributeDefinitions:
          - AttributeName: team1
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: team1
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1